version: 2
jobs:
   test:
     docker:
       - image: circleci/node:8
     working_directory: ~/circleci-demo
     steps:
       - checkout
       - run: 
          name: Test
          command: npm run test

workflows:
  version: 2
  commit:
    name: "commit"
    jobs:
      - test
  approval:
    name: "approval"
    jobs:
      - approve_build:
          type: approval
      - test:
          requires:
            - approve_build
  nightly:
    name: "nightly"
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
