version: 2
jobs:
   test:
     docker:
       - image: circleci/node:8
     steps:
       - checkout
       - run: 
          name: Test
          command: npm run test

workflows:
  version: 2
  commit:
    jobs:
      - test
  # Workflow for running e2e-tests at 12 am every night
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
